server:
  address: 0.0.0.0
  port: 8081
  servlet:
    application-display-name: CPS Belgium Parts-On-Line
    context-path: /

spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
#  flyway:
#    url: jdbc:postgresql://127.0.0.1:5432/
#    user: surplus
#    password: surplus
#    schemas: surplus
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/surplus
    username: surplus
    password: surplus
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    username: testcps24@gmail.com
    password: 123456789aB
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          ssl:
            enable: true
    port: 465